---
apiVersion: v1
kind: Service
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30007
      protocol: TCP
  selector:
    app: innsecure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innsecure
  template:
    metadata:
      labels:
        app: innsecure
  spec: null
containers:
  - name: innsecure
    image: form3/innsecure
    volumeMounts:
      - name: form3vol
        mountPath: /form3/example
securityContext:
  imagePullPolicy: Always
  allowPrivilegeEscalation: false
  runAsUser: 2000
ports:
  - containerPort: 8080
envFrom:
  - configMapRef:
      name: innsecure-config
