apiVersion: v1
kind: Service
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30007
      protocol: TCP
  selector:
    app: innsecure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innsecure
  namespace: innsecure
  labels:
    app: innsecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innsecure
  template:
    metadata:
      labels:
        app: innsecure
    spec:
      containers:
       - name: innsecure
          image: form3/innsecure
          livenessProbe: 
          httpGet:
          path: /prodhealth
          port: 8080
          resources:
          limits:
            cpu: 2
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
         securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 2001
          runAsUser: 1001
        volumeMounts:
        - mountPath: /certs
          name: kubernetes-dashboard-certs
        - mountPath: /tmp
          name: tmp-volume

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: innsecure-config        
